name: Deploy RoamGo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checking env
        run: echo ${{secrets.A2}}

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/Roamgotravels

            git pull origin main

            npm install
            pm2 stop roamgo_backend || true
            pm2 start backend/src/index.js --name roamgo_backend

            cd frontend
            npm install
            npm run build

            rm -rf /var/www/roamgotravels/*
            cp -r dist/* /var/www/roamgotravels/

            systemctl restart nginx

            pm2 save
